# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Submit a new Internal build to Google Play"
    lane :internal do
      sh("flutter build appbundle")
  
      c_dir = Dir.pwd
      puts "Current dir: #{c_dir}"
  
      target_dir = File.expand_path('../../build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib/', c_dir)
      puts "Target dir: #{target_dir}"
  
      if Dir.exist?(target_dir)
        sh("cd #{target_dir} && zip -r native_debug_symbols.zip arm64-v8a && mv native_debug_symbols.zip #{c_dir}")
      else
        puts "Directory does not exist: #{target_dir}"
        raise "Directory does not exist: #{target_dir}"
      end
  
      upload_to_play_store(
        track: 'internal',
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        skip_upload_changelogs: true,
        skip_upload_aab: false,
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        mapping_paths: ["./fastlane/native_debug_symbols.zip", "../build/app/outputs/mapping/release/mapping.txt"]
      )
    end
  end
